### ISSUE TITLE
AssertionError: You can only use one of gamma and epoch_decay

### ISSUE THREAD

**Issue by Aml-Hassan-Abd-El-hamid** [freshmanXB/DBDT#1]
Hi there, @freshmanXB 

First of all, I wanted to thank you for your work on that excellent paper and for making the code source open, I have been reading through your writing and I want to say that I really like your detailed explanation :)

I'm currently trying to use your code file that's called: "DBDT-Com", and I got this error:

```
Traceback (most recent call last):
  File "/home/aml/Downloads/DBDT-main/Script/DBDT-Com.py", line 281, in <module>
    optimizer = PDSCA(sdts,
  File "/home/aml/.local/lib/python3.10/site-packages/libauc/optimizers/pdsca.py", line 39, in __init__
    assert (gamma is None) or (epoch_decay is None), 'You can only use one of gamma and epoch_decay!'
AssertionError: You can only use one of gamma and epoch_decay!
```
I barely changed anything -only the paths from the data-, and I'm using the [European Credit Card Fraud from Kaggle](https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud), Can you please help me with fixing that problem?

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
Update:

I deleted the following code: ` gamma=gamma,` from:
```
    optimizer = PDSCA(sdts,
                      a=sdts.a,
                      b=sdts.b,
                      alpha=sdts.alpha,
                      lr=lr,
                      beta1=beta1,
                      beta2=beta2,
                      gamma=gamma,
                      margin=margin,
                      weight_decay=weight_decay)
```
and the code started to run, I'm not sure if that's the right thing to do or not though, so please let me know.

Also, I'm running that code on a Kaggle notebook with 16 g-GPU, and the training is taking so long, is there any way to have faster training?
Or since you used the same dataset in your paper, can you please share with me the final classification_report that you got cause I'm interested in the f1-score metric?
